# Generated by Django 4.2 on 2025-05-10 11:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={'verbose_name': 'ร้านค้า', 'verbose_name_plural': 'ร้านค้า'},
        ),
        migrations.RemoveField(
            model_name='store',
            name='is_surprise_box',
        ),
        migrations.AddField(
            model_name='store',
            name='additional_details',
            field=models.TextField(blank=True, help_text='รายละเอียดเพิ่มเติม เช่น ข้อมูลการลดขยะอาหารหรือนโยบายร้าน'),
        ),
        migrations.AlterField(
            model_name='store',
            name='additional_images',
            field=models.JSONField(blank=True, default=list, help_text='รายการ URL หรือพาธของรูปภาพเพิ่มเติม'),
        ),
        migrations.AlterField(
            model_name='store',
            name='allergen_ingredients',
            field=models.TextField(blank=True, help_text='ส่วนผสมที่อาจก่อให้เกิดอาการแพ้ (เช่น ถั่ว, กลูเตน)'),
        ),
        migrations.AlterField(
            model_name='store',
            name='discount_percentage',
            field=models.FloatField(default=0.0, help_text='ส่วนลดเป็นเปอร์เซ็นต์ (0-100%)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
    ]
