# Generated by Django 4.2 on 2025-05-10 17:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_store_options_alter_store_additional_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='available_from',
            field=models.TimeField(help_text='Store opening time (e.g., 12:00)'),
        ),
        migrations.AlterField(
            model_name='store',
            name='available_until',
            field=models.TimeField(help_text='Store closing time (e.g., 20:00)'),
        ),
        migrations.AlterField(
            model_name='store',
            name='discount_percentage',
            field=models.FloatField(default=0.0, help_text='Discount percentage (0-100%)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AlterField(
            model_name='store',
            name='price',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
