# Generated by Django 4.2 on 2025-05-10 16:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_store_options_remove_store_is_surprise_box_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={'verbose_name': 'Store', 'verbose_name_plural': 'Stores'},
        ),
        migrations.AlterField(
            model_name='store',
            name='additional_details',
            field=models.TextField(blank=True, help_text='Additional details, e.g., food waste reduction or store policies'),
        ),
        migrations.AlterField(
            model_name='store',
            name='additional_images',
            field=models.JSONField(blank=True, default=list, help_text='List of URLs or paths for additional images'),
        ),
        migrations.AlterField(
            model_name='store',
            name='allergen_ingredients',
            field=models.TextField(blank=True, help_text='Ingredients that may cause allergies (e.g., nuts, gluten)'),
        ),
        migrations.AlterField(
            model_name='store',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Discount percentage (0-100%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AlterField(
            model_name='store',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
