# Generated by Django 4.2 on 2025-05-13 06:47

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0006_alter_cart_options_remove_cart_session_key_cart_note_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='address_line',
        ),
        migrations.RemoveField(
            model_name='address',
            name='city',
        ),
        migrations.RemoveField(
            model_name='address',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='address',
            name='longitude',
        ),
        migrations.AddField(
            model_name='address',
            name='district',
            field=models.CharField(default='ไม่ระบุ', help_text='อำเภอ/เขต', max_length=100),
        ),
        migrations.AddField(
            model_name='address',
            name='phone_number',
            field=models.CharField(default='0000000000', help_text='เบอร์โทร 10 หลัก', max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'เบอร์โทรต้องเป็นตัวเลข 10 หลัก')]),
        ),
        migrations.AddField(
            model_name='address',
            name='province',
            field=models.CharField(default='ไม่ระบุ', help_text='จังหวัด', max_length=100),
        ),
        migrations.AddField(
            model_name='address',
            name='subdistrict',
            field=models.CharField(default='ไม่ระบุ', help_text='ตำบล/แขวง', max_length=100),
        ),
        migrations.AlterField(
            model_name='address',
            name='label',
            field=models.CharField(help_text='เช่น บ้าน, ที่ทำงาน', max_length=255),
        ),
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(help_text='รหัสไปรษณีย์ 5 หลัก', max_length=5, validators=[django.core.validators.RegexValidator('^\\d{5}$', 'รหัสไปรษณีย์ต้องเป็นตัวเลข 5 หลัก')]),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, help_text='เบอร์โทร 10 หลัก (ถ้ามี)', max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'เบอร์โทรต้องเป็นตัวเลข 10 หลัก')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
    ]
