# Generated by Django 4.2 on 2025-05-13 06:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_address_address_line_remove_address_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='district',
            field=models.CharField(help_text='อำเภอ/เขต', max_length=100),
        ),
        migrations.AlterField(
            model_name='address',
            name='phone_number',
            field=models.CharField(help_text='เบอร์โทร 10 หลัก', max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'เบอร์โทรต้องเป็นตัวเลข 10 หลัก')]),
        ),
        migrations.AlterField(
            model_name='address',
            name='province',
            field=models.CharField(help_text='จังหวัด', max_length=100),
        ),
        migrations.AlterField(
            model_name='address',
            name='subdistrict',
            field=models.CharField(help_text='ตำบล/แขวง', max_length=100),
        ),
    ]
