# Generated by Django 4.2 on 2025-05-25 17:05

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import myapp.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0008_alter_address_district_alter_address_phone_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'แท็ก',
                'verbose_name_plural': 'แท็ก',
            },
        ),
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'ที่อยู่', 'verbose_name_plural': 'ที่อยู่'},
        ),
        migrations.AlterModelOptions(
            name='allergy',
            options={'verbose_name': 'สารก่อภูมิแพ้', 'verbose_name_plural': 'สารก่อภูมิแพ้'},
        ),
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'ตะกร้า', 'verbose_name_plural': 'ตะกร้า'},
        ),
        migrations.AlterModelOptions(
            name='delivery',
            options={'verbose_name': 'การจัดส่ง', 'verbose_name_plural': 'การจัดส่ง'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'คำสั่งซื้อ', 'verbose_name_plural': 'คำสั่งซื้อ'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'รายการคำสั่งซื้อ', 'verbose_name_plural': 'รายการคำสั่งซื้อ'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'โปรไฟล์', 'verbose_name_plural': 'โปรไฟล์'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'รีวิว', 'verbose_name_plural': 'รีวิว'},
        ),
        migrations.AlterModelOptions(
            name='store',
            options={'verbose_name': 'ร้านค้า', 'verbose_name_plural': 'ร้านค้า'},
        ),
        migrations.AddField(
            model_name='address',
            name='address_line',
            field=models.CharField(default='', help_text='เลขที่, หมู่บ้าน, ถนน', max_length=255),
        ),
        migrations.AddField(
            model_name='address',
            name='is_default',
            field=models.BooleanField(default=False, help_text='ตั้งเป็นที่อยู่เริ่มต้น'),
        ),
        migrations.AddField(
            model_name='order',
            name='estimated_time',
            field=myapp.models.ThailandTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('pending', 'รอดำเนินการ'), ('assigned', 'มอบหมายแล้ว'), ('out_for_delivery', 'กำลังจัดส่ง'), ('completed', 'สำเร็จ')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('bank_transfer', 'โอนเงิน'), ('credit_card', 'บัตรเครดิต'), ('cash_on_delivery', 'เงินสดเมื่อรับ'), ('promptpay', 'พร้อมเพย์')], max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'รอดำเนินการ'), ('confirmed', 'ยืนยันแล้ว'), ('out_for_delivery', 'กำลังจัดส่ง'), ('completed', 'สำเร็จ'), ('cancelled', 'ยกเลิก')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='store',
            name='additional_details',
            field=models.TextField(blank=True, help_text='รายละเอียดเพิ่มเติม เช่น นโยบายลดขยะอาหาร'),
        ),
        migrations.AlterField(
            model_name='store',
            name='additional_images',
            field=models.JSONField(blank=True, default=list, help_text='รายการ URL หรือ path ของรูปภาพเพิ่มเติม'),
        ),
        migrations.AlterField(
            model_name='store',
            name='allergen_ingredients',
            field=models.TextField(blank=True, help_text='ส่วนผสมที่อาจก่อให้เกิดอาการแพ้ (เช่น ถั่ว, กลูเตน)'),
        ),
        migrations.AlterField(
            model_name='store',
            name='available_from',
            field=models.TimeField(help_text='เวลาเปิดร้าน (เช่น 12:00)'),
        ),
        migrations.AlterField(
            model_name='store',
            name='available_until',
            field=models.TimeField(help_text='เวลาปิดร้าน (เช่น 20:00)'),
        ),
        migrations.AlterField(
            model_name='store',
            name='discount_percentage',
            field=models.FloatField(default=0.0, help_text='เปอร์เซ็นต์ส่วนลด (0-100%)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('user', 'store')},
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('user', 'store')},
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['user', 'is_default'], name='myapp_addre_user_id_1b843e_idx'),
        ),
        migrations.AddIndex(
            model_name='allergy',
            index=models.Index(fields=['user', 'name'], name='myapp_aller_user_id_d969cc_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['user', 'store'], name='myapp_cart_user_id_0b7843_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['order', 'status'], name='myapp_deliv_order_i_ba8e4a_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['buyer', 'status', 'order_time'], name='myapp_order_buyer_i_c79363_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order', 'store'], name='myapp_order_order_i_f0544e_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['user'], name='myapp_profi_user_id_ad25ad_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['store', 'user', 'review_date'], name='myapp_revie_store_i_d094ac_idx'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['name', 'is_active'], name='myapp_store_name_08f87e_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['name'], name='myapp_tag_name_171f7c_idx'),
        ),
        migrations.AddField(
            model_name='store',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='stores', to='myapp.tag'),
        ),
    ]
